import { UserDTO } from "./Columns";
export const fakeUsers: UserDTO[] = [
  {
    id: "1",
    name: "Dr. Jean Dupont",
    email: "jean.dupont@clinique.com",
    role: "Admin",
    dateOfBirth: new Date(1980, 5, 15),
    phoneNumber: "+33 6 12 34 56 78",
    address: "12 Rue de la Paix, 75002 Paris, France",
  },
  {
    id: "2",
    name: "Marie Lambert",
    email: "marie.lambert@clinique.com",
    role: "User",
    dateOfBirth: new Date(1990, 8, 22),
    phoneNumber: "+33 6 98 76 54 32",
    address: "34 Avenue des Champs-Élysées, 75008 Paris, France",
  },
  {
    id: "3",
    name: "Admin Système",
    email: "admin@clinique.com",
    role: "Admin",
    dateOfBirth: new Date(1975, 2, 10),
    phoneNumber: "+33 6 55 44 33 22",
    address: "1 Rue de la République, 69001 Lyon, France",
  },
  {
    id: "4",
    name: "Patient Martin",
    email: "martin.patient@gmail.com",
    role: "Admin",
    dateOfBirth: new Date(1995, 11, 5),
    phoneNumber: "+33 6 11 22 33 44",
    address: "56 Boulevard Saint-Germain, 75005 Paris, France",
  },
  {
    id: "5",
    name: "Dr. Sophie Bernard",
    email: "sophie.bernard@clinique.com",
    role: "Admin",
    dateOfBirth: new Date(1982, 4, 18),
    phoneNumber: "+33 6 77 88 99 00",
    address: "78 Rue de Rivoli, 75004 Paris, France",
  },
  {
    id: "6",
    name: "Admin Claude",
    email: "claude.leroy@example.com",
    role: "Admin",
    dateOfBirth: new Date(1988, 7, 30),
    phoneNumber: "+33 6 33 22 11 00",
    address: "90 Avenue de la Grande Armée, 75016 Paris, France",
  },
];